---
hibernate:
    cache:
        queries: false
        use_query_cache: false
        use_second_level_cache: false
        provider_class: net.sf.ehcache.hibernate.EhCacheProvider
        region:
            factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

dataSource:
    pooled: true
    jmxExport: true

environments:
    development:
        grails:
            # assets:
            #     storagePath: '/tmp/assets'
            plugin:
                fields:
                    disableLookupCache: true
        dataSource:
            driverClassName: org.h2.Driver
            username: sa
            password:
            dbCreate: create-drop
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    # -- for DB change log --
    change:
        dataSource:
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: 'linchinghui'
            password: 'cces168'
            dbCreate: none
            url: 'jdbc:mysql://192.168.0.201:3306/cces?useUnicode=true&characterEncoding=UTF-8&useSSL=false'
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState;StatementCache(max=200) #ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    production:
        grails:
            assets:
                bundle: true
                # storagePath: '/var/www/cces/assets'
                excludes:
                    - '**/*.unminified.js'
                    - '**/*.less'
                    - '**/iefix'
                minifyOptions:
                    excludes:
                        - '**/*.unminified.js'
                        - '**/*.less'
                        - '**/iefix'
        dataSource:
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: 'linchinghui'
            password: 'cces168'
            dbCreate: validate
            url: 'jdbc:mysql://localhost:3306/cces?useUnicode=true&characterEncoding=UTF-8&useSSL=false'
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState;StatementCache(max=200) #ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
# ---
# grails:
#     profile: web
#     codegen:
#         defaultPackage: com.lch.cces
#     spring:
#         transactionManagement:
#             proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    profile: web
    codegen:
        defaultPackage: com.lch.cces
    spring:
        transactionManagement:
            proxies: false
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    web:
        disable:
            multipart: false
    controllers:
        defaultScope: singleton
        # upload:
        #     # maxFileSize:    2500000
        #     # maxRequestSize: 2500000
        #     maxInMemorySize:    2500000
        #     maxUploadSize: 2500000
    converters:
        encoding: UTF-8
        # domain:
        #     include:
        #         class: true
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    gorm:
        failOnError: true
        # default:
        #     mapping:
        #         - 'user-type' :
        #             type: com.lch.cces.PhotoUserType
        #             class: com.lch.cces.Photo
    resources:
        # --- for issue #9908 ---
        pattern: '/**'
    cache:
        enabled: true
        # clearAtStartup: true
    #     config:
    #         - cache:
    #             name: 'function'
    #         - cache:
    #             name: 'privilege'
    #         - cache:
    #             name: 'role'
    #         - cache:
    #             name: 'materialCategory'
    #         - cache:
    #             name: 'vehicleBrand'
---
endpoints:
    enabled: false
    info:
        enabled: true
    health:
        enabled: true
    shutdown:
        enabled: true
    jmx:
        unique-names: true
# ---
# grails:
#     gorm:
#         failOnError: true
#     resources:
#         # --- for issue #9908 ---
#         pattern: '/**'
#     cache:
#         enabled: true
#         # clearAtStartup: true
#     #     config:
#     #         - cache:
#     #             name: 'function'
#     #         - cache:
#     #             name: 'privilege'
#     #         - cache:
#     #             name: 'role'
#     #         - cache:
#     #             name: 'materialCategory'
#     #         - cache:
#     #             name: 'vehicleBrand'
# ---
# server:
#     contextPath: '/cces'
# ---
# crash:
#     web:
#         enabled: true
